language: node_js
os: osx
node_js:
  - "8"
before_install:
  - cd ./magiccap
  - brew install p7zip
script:
  - npm run lint
  - npm run maccompile
  - npm run install-linux-deps
  - npm run linuxcompile
  - cd ./build
  - mv ./MagicCap.dmg ./magiccap-mac.dmg
  - cd ./MagicCap-linux-x64
  - 7z a ../magiccap-linux.zip *
  - cd ../
