language: node_js
os: osx
node_js:
  - "8"
before_install:
  - cd ./magiccap
  - brew install p7zip fakeroot dpkg
script:
  - npm run lint
  - npm run maccompile
  - npm run install-linux-deps
  - npm run linuxcompile
  - mv ./build/MagicCap.dmg ./build/magiccap-mac.dmg
  - cd ./build/MagicCap-linux-x64
  - 7z a ../magiccap-linux.zip *
  - cd ../
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - magiccap-linux.zip
    - magiccap-mac.dmg
  skip_cleanup: true
  on:
    tags: true
